# Generated by Django 3.2.16 on 2022-10-08 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0011_logentry_serialized_data"),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=40, null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('full_path', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Request Log',
                'verbose_name_plural': 'User Request Logs',
            },
        ),
    ]
